title: "Affiliates"
email: matheuscostadosantos@hotmail.com
timezone: UTC
baseurl: "/blog"
url: "https://matheuscostadesign.github.io"
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: Matheus Costa
paginate: 30
disqus: "demowebsite"
locale: pt-BR
lang: pt-BR
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  matheus:
    name: Matheus Costa
    display_name: Matheus Costa
    avatar: "assets/images/matheus.jpg"
    email: matheuscostadosantos@hotmail.com
    web: https://matheuscostadesign.github.io/
    twitter: https://www.instagram.com/matheuscosta.design/
    description: "Desenvolvedor Front-end e UX/UI Designer. 
    Compartilhando conhecimentos sobre tecnologias para desenvolvimento web e design de interfaces"
  # john:
  #   name: John
  #   display_name: John
  #   avatar: "assets/images/john.png"
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net/category/jekyll-themes/
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/matheuscosta.design/
  facebook: https://www.facebook.com/matheuscostadev
  # twitter: https://twitter.com/bstartercom

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
